postgresql-git:
  image: valilabis.ensg.eu:5000/pgsql
  environment:
    - DB_NAME=${DBGITNAME}
    - DB_USER=${DBGITLOGIN}
    - DB_PASS=${DBGITPASSWORD}
    - DB_EXTENSION=pg_trgm
  volumes:
    - "/srv/docker/gitlab/pgsql:/var/lib/postgresql"
  restart: always

redis:
  image: valilabis.ensg.eu:5000/gitredis
  volumes:
    - "/srv/docker/gitlab/redis:/var/lib/redis"
  restart: always

gitlab:
  image: valilabis.ensg.eu:5000/gitlab
  environment:
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string
    - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alpha-numeric-string
    - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alpha-numeric-string
  volumes:
    - "/srv/docker/gitlab/gitlab:/home/git/data"
  links:
    - postgresql-git:postgresql
    - redis:redisio
  ports:
    - "10022:22"
    - "10089:80"
  restart: always

postgresql-red:
  image: valilabis.ensg.eu:5000/pgsql
  environment:
    - DB_NAME=${DBREDNAME}
    - DB_USER=${DBREDLOGIN}
    - DB_PASS=${DBREDPASSWORD}
  volumes:
    - "/srv/docker/redmine/pgsql:/var/lib/postgresql"
  restart: always

redmine:
  build: ./redmine
  volumes:
    - "/srv/docker/redmine/redmine:/home/redmine/data"
  links:
    - postgresql-red:postgresql
  ports:
    - "10090:80"
  restart: always

jenkins:
  build: ./jenkins
  environment:
    - log_in=${log_in}
    - password=${password}
  volumes:
    - "/srv/docker/jenkins:/jenkins/jobs"
  ports:
    - "10091:8080"
  restart: always

dokuwiki:
  build: ./dokuwiki
  environment:
    - log_in=${log_in}
    - password=${password}
    - name=${name}
    - address=${address}

  volumes:
    - "/srv/docker/dokuwiki:/home/dokuwiki/data"
  ports:
    - "10092:80"
  restart: always

forge:
  build: ./web-forge
  volumes:
    - "/srv/docker/forge:/home/forge/data"
    - "/etc/hostname:/etc/hostname"
  ports:
    - "8080:80"
  restart: always

user-creator:
  build: ./user-creator
  environment:
    - log_in=${log_in}
    - password=${password}
    - name=${name}
    - lastname=${lastname}
    - address=${address}
    - DBGITNAME=${DBGITNAME}
    - DBGITLOGIN=${DBGITLOGIN}
    - DBGITPASSWORD=${DBGITPASSWORD}
    - DBREDNAME=${DBREDNAME}
    - DBREDLOGIN=${DBREDLOGIN}
    - DBREDPASSWORD=${DBREDPASSWORD}
    - HOOKED=0
  links:
    - postgresql-git:postgresql-git
    - postgresql-red:postgresql-red
    - redmine:redmine
    - jenkins:jenkins
    - gitlab:gitlab
    - dokuwiki:dokuwiki
